version: '3.8'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:3000
    environment:
      #- environment=production
      - PORT=3000
    env_file:
      - .env
  cadvisor:
    depends_on:
      - webapp
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true

  node-exporter:
    depends_on:
      - webapp
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(dev|proc|sys|var/lib/docker/.+)($|/)'
  nginxlog-exporter:
    image: quay.io/martinhelmich/prometheus-nginxlog-exporter:latest
    container_name: nginxlog_exporter
    restart: unless-stopped
    ports:
      - "9113:4040"
    volumes:
      - /var/log/nginx:/var/log/nginx:ro
      - ./nginxlog-config.hcl:/etc/nginxlog-exporter/config.hcl:ro
    command:
      - --config-file=/etc/nginxlog-exporter/config.hcl
    depends_on:
      - webapp
      