version: '3.8'

services:
  tapshopjazzcash:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"   #changeport
    env_file:
      - .env
      - /opt/elasticbeanstalk/deployment/env.list
      
